### ISSUE TITLE
aligenmc -g Herwig fails

### ISSUE THREAD

**Issue by yschutz** [alisw/aligenmc#4]
alienv enter VO_ALICE@AliGenerators::v20190909-1
aligenmc -g herwig
Herwig: ThePEG::Exception caught.
While reading object number 463 of class <UNKNOWN>:
PersistentIStream could not find the class 'ThePEG::FastJetFinder'.
error message from dynamic loader:
/cvmfs/alice.cern.ch/el6-x86_64/Packages/Herwig/v7.1.2-alice1-9/lib/Herwig/FastJetFinder.so: cannot open shared object file: No such file or directory
/cvmfs/alice.cern.ch/el6-x86_64/Packages/Herwig/v7.1.2-alice1-9/lib/Herwig/FastJetFinder.dylib: cannot open shared object file: No such file or directory
/build/workarea/sw/20156049/1/INSTALLROOT/4cb2a4f4682ca9be778da465d80c95721ee3272a/slc6_x86-64/ThePEG/v2.1.2-8/lib/ThePEG/FastJetFinder.so: cannot open shared object file: No such file or directory
/build/workarea/sw/20156049/1/INSTALLROOT/4cb2a4f4682ca9be778da465d80c95721ee3272a/slc6_x86-64/ThePEG/v2.1.2-8/lib/ThePEG/FastJetFinder.dylib: cannot open shared object file: No such file or directory
./FastJetFinder.so: cannot open shared object file: No such file or directory
./FastJetFinder.dylib: cannot open shared object file: No such file or directory
/cvmfs/alice.cern.ch/el6-x86_64/Packages/Herwig/v7.1.2-alice1-9/lib/Herwig/FastJetFinder.so: cannot open shared object file: No such file or directory
/cvmfs/alice.cern.ch/el6-x86_64/Packages/Herwig/v7.1.2-alice1-9/lib/Herwig/FastJetFinder.dylib: cannot open shared object file: No such file or directory
/FastJetFinder.so: cannot open shared object file: No such file or directory
/FastJetFinder.dylib: cannot open shared object file: No such file or directory
libgmp.so.3: cannot open shared object file: No such file or directory
FastJetFinder.dylib: cannot open shared object file: No such file or directory

**Comment by mfasDa** [comment]
Has been fixed with recent Herwig builds ~June 2020. Try one of the latest builds of AliGenerators.
